name: Hello Flow
on:
  push
jobs:
  first-job:
	runs-on: ubuntu-latest
	steps:
  	- name: Diga oi
    	run: echo "Hello World!"
  	- name: Diga valeu
    	run: echo "Valeu - bye!"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
